### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by zhuangya** [sivan/heti#1]
Hi

首先赞美一下这个项目的出众效果 :)

不过我看项目中并没有 [License File](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository)

只是 `package.json` 里面写了一个 MIT

所以：是不是决定用 MIT License 呢？
无论是用什么 License 还是显式的声明成 License File 比较好吧？

**Comment by sivan** [comment]
@zhuangya 项目刚开始写，所以漏掉了。已经补上，是 MIT :P
