### ISSUE TITLE
请问该如何在 Docusaurus 项目中使用增强脚本呢？

### ISSUE THREAD

**Issue by dofine** [sivan/heti#111]
通过添加css之后常规样式可以正常显示，但不知道如何使用增强脚本。或者说这个issue应该在 docusaurus 项目中提问？感谢！

**Comment by sivan** [comment]
在它完成文档内容的渲染后手动触发应该就可以了：
https://github.com/sivan/heti#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
