### ISSUE TITLE
应用在 Hexo 生成的页面时 pre code 内代码错乱

### ISSUE THREAD

**Issue by dofine** [sivan/heti#35]
加了 `<article class="post heti">` 之后代码框成了这个样式
![image](https://user-images.githubusercontent.com/440101/96835401-1cfd7080-1476-11eb-9575-00609ade3057.png)

不知道应该提在 Hexo 主题的 repo 还是这里？如有打扰请见谅~

**Comment by sivan** [comment]
> 加了 `<article class="post heti">` 之后代码框成了这个样式
> 
> ![image](https://user-images.githubusercontent.com/440101/96835401-1cfd7080-1476-11eb-9575-00609ade3057.png)
> 
> 
> 
> 不知道应该提在 Hexo 主题的 repo 还是这里？如有打扰请见谅~
> 
> 

你好，方便把hexo主题仓库贴一下吗？我先去看看

**Comment by dofine** [comment]
> > 加了 `<article class="post heti">` 之后代码框成了这个样式
> > ![image](https://user-images.githubusercontent.com/440101/96835401-1cfd7080-1476-11eb-9575-00609ade3057.png)
> > 不知道应该提在 Hexo 主题的 repo 还是这里？如有打扰请见谅~
> 
> 你好，方便把hexo主题仓库贴一下吗？我先去看看

你好~  
https://github.com/ahonn/hexo-theme-even 用的这个第三方主题~

**Comment by sivan** [comment]
@dofine 看了一下，是代码格式化后嵌到一个 `<figure class="highlight">` 标签里导致的，可以试试加下面这行代码看能否修复？
```css
figure.highlight { text-align: left; }
```

**Comment by dofine** [comment]
> @dofine 看了一下，是代码格式化后嵌到一个 `<figure class="highlight">` 标签里导致的，可以试试加下面这行代码看能否修复？
> 
> ```css
> figure.highlight { text-align: left; }
> ```

可以了！非常感谢~~ ！
