### ISSUE TITLE
关于中文「强调/粗体」的样式选择

### ISSUE THREAD

**Issue by Mongkii** [sivan/heti#37]
在印刷版书籍中，强调/粗体往往用其他字体（通常是黑体/楷体）表示，请问 heti 会考虑改为这种样式吗？

**Comment by sivan** [comment]
@Mongkii 你值得是「传统」预设中的着重文本吗？我主要是参考 [《中文排版需求》](https://w3c.github.io/clreq/#hei) 设置的字体，有提到「内文中也会使用字重较粗的黑体作为特定文字的强调、着重」。当时可能确实是考虑欠妥，后续会把「传统」预设中的`<em>`设成黑体。

有更多好的信息或参考材料欢迎交流。

**Comment by sivan** [comment]
0.8.1 已修改
