### ISSUE TITLE
Non-character behaviour for styled quote

### ISSUE THREAD

**Issue by tabokie** [sivan/heti#43]
`<q></q>` effectively inserts `「」` or `""` around a quote, depending on the context, but the inserted symbol can't be selected or copied like normal characters. Is this an expected behaviour?

Reproduce screenshot:
![image](https://user-images.githubusercontent.com/27005812/101592235-e0d39e80-3a28-11eb-88a1-a5c89130becb.png)
![image](https://user-images.githubusercontent.com/27005812/101592311-ff399a00-3a28-11eb-8405-7f3197244ba7.png)

**Comment by sivan** [comment]
@tabokie yes, because `<q></q>` inserts quotation marks by pseudo-elements, which are not present in the DOM. So they are not selectable.

**Comment by tabokie** [comment]
Thanks for the reply. I strongly suggest considering resolving this issue in future improvements, I personally found it unpleasant and causing problem when copying large chunks of text.
