### ISSUE TITLE
添加代码后文章排版不对齐

### ISSUE THREAD

**Issue by xzyone** [sivan/heti#53]
添加代码前：
![image](https://user-images.githubusercontent.com/23356216/120826224-c704b580-c58c-11eb-9a03-727219cfc3ee.png)

添加代码后：
![image](https://user-images.githubusercontent.com/23356216/120826255-d08e1d80-c58c-11eb-904f-a076f0c504de.png)

麻烦大佬查看下

**Comment by sivan** [comment]
@xzyone 因为考虑到中文的最大行长，所以设置了最大值。超过这个值容易影响阅读效果。
去掉它也很简单，删掉 `.heti` 样式中的 `max-width: 42em;` 就好了~

**Comment by xzyone** [comment]
感谢指导！

**Comment by xzyone** [comment]
还有一个问题，好像用了Heti之后，文本居中就失效了，请问这个要怎么解决呢

**Comment by sivan** [comment]
> 还有一个问题，好像用了Heti之后，文本居中就失效了，请问这个要怎么解决呢

没有类似的设置，可能是样式嵌套导致的污染。可以搞一个demo看一下吗？
