### ISSUE TITLE
国标引号

### ISSUE THREAD

**Issue by liyishuai** [sivan/heti#62]
开发者您好，感谢您对项目的辛勤付出！

https://github.com/sivan/heti/blob/c58ee4a39ebf7bb2e41ae6f42eb8f613563258d6/lib/_inline.scss#L83-L91

根据中华人民共和国国家标准GB/T 15834-2011《标点符号用法》，第4.8节、5.2.3节，引号在横排文稿中应为“弯引号”，在竖排文稿中应为『双引号在外，「单引号」在内』。请问是否考虑新增标签选项以兼容国标？谢谢！

**Comment by liyishuai** [comment]
另根据国标4.8.3.5节，多段引用：
```html
<q>
<p>第一段。</p>
<p>第二段。</p>
<p>第三段。</p>
</q>
```
只在最后一段末尾用后引号：
```
“第一段。
“第二段。
“第三段。”
```

**Comment by sivan** [comment]
> 根据中华人民共和国国家标准GB/T 15834-2011《标点符号用法》，第4.8节、5.2.3节，引号在横排文稿中应为“弯引号”，在竖排文稿中应为『双引号在外，「单引号」在内』。请问是否考虑新增标签选项以兼容国标？谢谢！

好的，我改成一个配置选项兼容两者。要稍晚几天处理。

**Comment by sivan** [comment]
> 根据中华人民共和国国家标准GB/T 15834-2011《标点符号用法》，第4.8节、5.2.3节，引号在横排文稿中应为“弯引号”，在竖排文稿中应为『双引号在外，「单引号」在内』。请问是否考虑新增标签选项以兼容国标？谢谢！

已在0.9.2中添加，通过源码引用的方式覆盖`_variables.scss`文件中`$chinese-quote-set`变量的值为`cn`即可将引号设为GB/T 15834-2011的国家标准。

---

> 另根据国标4.8.3.5节，多段引用：
> 只在最后一段末尾用后引号：

`<q>`是内联元素不能用来嵌套`<p>`，所以这个场景里可能用`<blockquote>`或者多个`<p><q>……</q></p>`更合适。但都与规范的样式有一些差异，暂时先不作处理。

**Comment by liyishuai** [comment]
请教一下使用方法：
https://github.com/sivan/heti/blob/40a4dbce866a8f61fc33ddd73e1de0137aa7148f/_site/index.html#L397
此段文档我没读懂，可能是不太熟悉SCSS的缘故。目前摸索出的方法（liyishuai/heti@6a3d6397cd5809666e9124778a7add4ba9aeebe6）是在`lib/heti.scss`中设置了`$chinese-quote-set`变量，并重新编译`heti.min.css`文件。请问这是文档的本意吗？如果是，可考虑修改得更具体些：
> 修改`lib/heti.scss`，在`@import "variables";`前加入`$chinese-quote-set: "cn";`以覆盖`_variables.scss`文件中的`$chinese-quote-set`变量；重新编译`heti.min.css`并通过源码引用之。

**Comment by sivan** [comment]
> 请教一下使用方法：
> 
> https://github.com/sivan/heti/blob/40a4dbce866a8f61fc33ddd73e1de0137aa7148f/_site/index.html#L397
> 
> 
> 此段文档我没读懂，可能是不太熟悉SCSS的缘故。目前摸索出的方法（ [liyishuai/heti@6a3d639](https://github.com/liyishuai/heti/commit/6a3d6397cd5809666e9124778a7add4ba9aeebe6)）是在`lib/heti.scss`中设置了`$chinese-quote-set`变量，并重新编译`heti.min.css`文件。请问这是文档的本意吗？如果是，可考虑修改得更具体些：
> > 修改`lib/heti.scss`，在`@import "variables";`前加入`$chinese-quote-set: "cn";`以覆盖`_variables.scss`文件中的`$chinese-quote-set`变量；重新编译`heti.min.css`并通过源码引用之。

是的，如果单独引用`heti.min.css`的话就要重新编译。
