### ISSUE TITLE
斜体显示为黑体

### ISSUE THREAD

**Issue by moi-mo** [sivan/heti#69]
在我的博客一篇博文中，原文用```* *```标注的斜体被显示为黑体

请参见下方comment中图片，博客平台为Jekyll

**Comment by moi-mo** [comment]
此外pc端和手机端的显示也不一致
![image](https://user-images.githubusercontent.com/50516170/149896076-1fb12fa8-8ac0-4ff9-96cd-36ffeb2d0eb8.png)
![image](https://user-images.githubusercontent.com/50516170/149896323-d7d114db-d2af-4bb2-b8c2-6816d1a5e497.png)

**Comment by sivan** [comment]
> 在我的博客一篇博文中，原文用`* *`标注的斜体被显示为黑体
> 
> 请参见下方comment中图片，博客平台为Jekyll

目前中文的斜体几乎都是通过算法暴力变形实现的，效果比较生硬不好看。所以项目内在中文里刻意避免了斜体展示，换成了加粗的样式。
建议的方式是用[着重号（使用class实现）](https://sivan.github.io/heti/#tags)或者手写体来表示强调，但考虑到大部分用户很少会把`* *`用在这种场景，所以就没设成默认样式。

手机端的问题可能是系统里没有对应中文字体的粗体字体导致的，这个安卓端的兼容不太一致。
