### ISSUE TITLE
[Bug] 宋体强调没有加粗

### ISSUE THREAD

**Issue by XieJiSS** [sivan/heti#73]
![image](https://user-images.githubusercontent.com/24671280/150270900-4a04d341-f6a8-40c9-aae4-f0b5af9a7b54.png)

然而如果我手动将 `--classic` CSS 选择器中的 `"Heti Song"` 换为 `"Songti SC Regular", "Songti TC Regular", "SimSun"`，则可以显示加粗效果：

![image](https://user-images.githubusercontent.com/24671280/150271025-e4fb97b1-72ed-4e64-9c92-0ea814d3aaa8.png)

**Comment by sivan** [comment]
应该是字体问题，windows我没测试。近期我修一下。
