### ISSUE TITLE
autoSpacing not working

### ISSUE THREAD

**Issue by Ahdw** [sivan/heti#76]
<img width="579" alt="autospacing" src="https://user-images.githubusercontent.com/6417649/150478047-767ae2fa-27b1-4d30-860d-94b317e2cc20.png">

我给文章部分加上了 heti class，可以看到 heti--classic 的样式生效了。

按照说明，我在 `</body>`之前加上了增强脚本的调用，可是却没有生效。

`<heti-adjacent class="heti-adjacent-half"></heti-adjacent>` 没有自动插入标点符号之间。
<img width="494" alt="html" src="https://user-images.githubusercontent.com/6417649/150478975-f0858a27-430e-42ba-b3fa-627ed7ec2b39.png">
<img width="348" alt="punctualation" src="https://user-images.githubusercontent.com/6417649/150479000-4f40376a-1efd-4149-b394-e4d6f65c02a1.png">

在 Chrome 和 Safari 上都没有生效。

**Comment by sivan** [comment]
entry 里的内容是动态渲染的吗？

**Comment by shikelong** [comment]
The same issue.

Tech Stack: Gatsby / React

I try execute autoSpacing in Console. But It not work.

![image](https://user-images.githubusercontent.com/4499997/151083357-134c2ebe-fe39-4eb8-a39a-22a18c8713a3.png)

![image](https://user-images.githubusercontent.com/4499997/151083392-32eeb3c7-ca6a-42ec-befa-a2e6e56dcc8d.png)

![image](https://user-images.githubusercontent.com/4499997/151083675-307c914f-6069-47d8-9ae0-c0303d9066cb.png)


Chrome version: Version 97.0.4692.71 (Official Build) (arm64) on M1

**Comment by Ahdw** [comment]
@sivan 是 Hexo 的主题，我在[这一行](https://github.com/tufu9441/maupassant-hexo/blob/master/layout/base.pug#L47)下面加了引用脚本的line：
<img width="711" alt="Snipaste_2022-01-27_21-45-55" src="https://user-images.githubusercontent.com/6417649/151371146-45f134bd-d1f9-4d61-9e8f-fec97a128ee1.png">

Issue 最上面的截图显示，编译出的 html 看起来是正确的，但是 auto spacing 却没有生效。我自己也不清楚这算不算你说的「动态渲染」

**Comment by hyrious** [comment]
`<script>` 不能同时包含 `src` 和内容，当同时存在时只有 `src` 会生效。

另外 `autoSpacing` 使用了 [DOMContentLoaded](https://github.com/sivan/heti/blob/eadee6a3b748b3b7924a9e7d5b395d4bce479c9a/js/heti-addon.js#L121)，在页面加载完后监听这个事件也什么都不会发生。
