### ISSUE TITLE
把 构建最终的 css 和 发布 gh pages 以及发布到 npm 自动化？

### ISSUE THREAD

**Issue by zhuangya** [sivan/heti#8]
有没有兴趣搞成自动化？

**Comment by zhuangya** [comment]
这里增加了用来做 test 和 build 的 github action https://github.com/zhuangya/heti/tree/npm-files

这里有意写了个错误 https://github.com/zhuangya/heti/tree/oops

你觉得如何？ @sivan

**Comment by sivan** [comment]
@zhuangya 赞👍🏻 之前没用过 GitHub Action，刚把文档发布搞明白 :-(
