### ISSUE TITLE
请问如何在hexo中使用

### ISSUE THREAD

**Issue by YangguangZhou** [sivan/heti#90]

**Comment by LolipopJ** [comment]
编辑主题 `layout` 目录中的布局文件，在主题的 `<head>` 中添加 `<link rel="stylesheet" href="https://unpkg.com/heti/umd/heti.min.css">` 全局引入 `heti`，然后给文章容器添加 `heti` 作为样式类。

---

以 Archer 主题为例，可以先在全局布局（[`layout/layout.ejs`](https://github.com/fi3ework/hexo-theme-archer/blob/master/layout/layout.ejs)）文件引入 `heti`：

```ejs
<!DOCTYPE html>
<html lang="<%- config.language %>">
    <head>
        <link rel="stylesheet" href="https://unpkg.com/heti/umd/heti.min.css">
    </head>
    <!-- 其他的代码 -->
</html>
```

然后修改文章页布局（[`layout/post.ejs`](https://github.com/fi3ework/hexo-theme-archer/blob/master/layout/post.ejs)）文件，为 `<article>` 标签添加 `heti` 样式类：

```ejs
<main class="main post-page">
    <article class="article-entry heti">
        <%- page.content %>
    </article>
    <!-- 其他的代码 -->
</main>
```
